- name: Update the apt package index
  become: yes
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install packages for apt add repository over HTTPS
  become: yes
  ansible.builtin.apt:
    name: "{{ docker_debian_dependencies }}"
    force_apt_get: yes
    state: latest
    update_cache: yes


- name: Check if docker key exists
  ansible.builtin.stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker_gpg

- name: Create APT keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download docker armored signature
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /tmp/docker.asc
  when: not docker_gpg.stat.exists

- name: Dearmor docker asc
  ansible.builtin.command: /usr/bin/gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.asc
  when: not docker_gpg.stat.exists

- name: Add docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
    filename: docker

- name: Install docker
  ansible.builtin.apt:
    state: latest
    pkg:
    - docker-ce
    - docker-ce-cli
    - docker-ce-rootless-extras
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
